const ship = [
    {
      "name": "Exec S",
      "id": "tahlan_Exec_S",
      "designation": "Assault Drone",
      "tech/manufacturer": "",
      "system id": "",
      "fleet pts": "",
      "hitpoints": 150,
      "armor rating": 30,
      "max flux": 500,
      "8/6/5/4%": "",
      "flux dissipation": 100,
      "ordnance points": 0,
      "fighter bays": "",
      "max speed": 300,
      "acceleration": 300,
      "deceleration": 250,
      "max turn rate": 90,
      "turn acceleration": 180,
      "mass": 30,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 360,
      "shield upkeep": 0,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": "",
      "fuel": "",
      "fuel/ly": "",
      "range": "",
      "max burn": "",
      "base value": "",
      "cr %/day": "",
      "CR to deploy": "",
      "peak CR sec": "",
      "CR loss/sec": "",
      "supplies/rec": "",
      "supplies/mo": "",
      "hints": "HIDE_IN_CODEX",
      "tags": "",
      "rarity": "",
      "breakProb": 0,
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": 565656
    },
    {
      "name": "Exec M",
      "id": "tahlan_Exec_M",
      "designation": "Combat Drone",
      "tech/manufacturer": "",
      "system id": "",
      "fleet pts": "",
      "hitpoints": 300,
      "armor rating": 50,
      "max flux": 1000,
      "8/6/5/4%": "",
      "flux dissipation": 100,
      "ordnance points": 0,
      "fighter bays": "",
      "max speed": 300,
      "acceleration": 300,
      "deceleration": 250,
      "max turn rate": 90,
      "turn acceleration": 180,
      "mass": 30,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 360,
      "shield upkeep": 0,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": "",
      "fuel": "",
      "fuel/ly": "",
      "range": "",
      "max burn": "",
      "base value": "",
      "cr %/day": "",
      "CR to deploy": "",
      "peak CR sec": "",
      "CR loss/sec": "",
      "supplies/rec": "",
      "supplies/mo": "",
      "hints": "HIDE_IN_CODEX",
      "tags": "",
      "rarity": "",
      "breakProb": 0,
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": 565656
    },
    {
      "name": "TuRRmeeNaYtor",
      "id": "tahlan_turrmy",
      "designation": "Drone",
      "tech/manufacturer": "Pirate",
      "system id": "",
      "fleet pts": "",
      "hitpoints": 150,
      "armor rating": 50,
      "max flux": 100,
      "8/6/5/4%": "",
      "flux dissipation": 50,
      "ordnance points": "",
      "fighter bays": "",
      "max speed": 300,
      "acceleration": 300,
      "deceleration": 300,
      "max turn rate": 100,
      "turn acceleration": 200,
      "mass": 10,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": "",
      "fuel": "",
      "fuel/ly": "",
      "range": "",
      "max burn": "",
      "base value": "",
      "cr %/day": "",
      "CR to deploy": "",
      "peak CR sec": "",
      "CR loss/sec": "",
      "supplies/rec": "",
      "supplies/mo": "",
      "hints": "HIDE_IN_CODEX",
      "tags": "",
      "rarity": "",
      "breakProb": 0,
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": 454
    }
  ]

  export default ship