const ships= [
    {
      "name": "Yosei",
      "id": "tahlan_Yosei",
      "designation": "Frigate",
      "tech/manufacturer": "High Tech",
      "system id": "highenergyfocus",
      "fleet pts": 8,
      "hitpoints": 1400,
      "armor rating": 200,
      "max flux": 3000,
      "8/6/5/4%": "",
      "flux dissipation": 250,
      "ordnance points": 55,
      "fighter bays": 1,
      "max speed": 140,
      "acceleration": 180,
      "deceleration": 175,
      "max turn rate": 90,
      "turn acceleration": 270,
      "mass": 200,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.3,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 15,
      "max crew": 25,
      "cargo": 30,
      "fuel": 20,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 11,
      "base value": 38000,
      "cr %/day": 10,
      "CR to deploy": 20,
      "peak CR sec": 180,
      "CR loss/sec": 0.25,
      "supplies/rec": 8,
      "supplies/mo": 8,
      "hints": "",
      "tags": "rare_bp, hist1t",
      "rarity": 0.75,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 2,
      "travel drive": "",
      "number": 206
    },
    {
      "name": "Trill",
      "id": "tahlan_Trill",
      "designation": "Catalyst Frigate",
      "tech/manufacturer": "High Tech",
      "system id": "displacer",
      "fleet pts": 5,
      "hitpoints": 1200,
      "armor rating": 300,
      "max flux": 2500,
      "8/6/5/4%": "",
      "flux dissipation": 300,
      "ordnance points": 35,
      "fighter bays": "",
      "max speed": 150,
      "acceleration": 160,
      "deceleration": 110,
      "max turn rate": 60,
      "turn acceleration": 120,
      "mass": 250,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 360,
      "shield upkeep": 0.3,
      "shield efficiency": 0.6,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": 10,
      "fuel": 10,
      "fuel/ly": 1,
      "range": 10,
      "max burn": 10,
      "base value": 40000,
      "cr %/day": 5,
      "CR to deploy": 10,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 8,
      "supplies/mo": 8,
      "hints": "HIDE_IN_CODEX",
      "tags": "rare_bp, hist1t",
      "rarity": 0.2,
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 2,
      "travel drive": "",
      "number": 59429
    },
    {
      "name": "Korikaze",
      "id": "tahlan_Korikaze",
      "designation": "Drone Frigate",
      "tech/manufacturer": "High Tech",
      "system id": "displacer",
      "fleet pts": 5,
      "hitpoints": 2000,
      "armor rating": 300,
      "max flux": 2800,
      "8/6/5/4%": "",
      "flux dissipation": 200,
      "ordnance points": 45,
      "fighter bays": "",
      "max speed": 130,
      "acceleration": 160,
      "deceleration": 110,
      "max turn rate": 60,
      "turn acceleration": 120,
      "mass": 250,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 180,
      "shield upkeep": 0.4,
      "shield efficiency": 0.6,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": 20,
      "fuel": 20,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 9,
      "base value": 40000,
      "cr %/day": 5,
      "CR to deploy": 10,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 5,
      "supplies/mo": 5,
      "hints": "HIDE_IN_CODEX",
      "tags": "tahlan_kaze_bp",
      "rarity": 0.5,
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 2,
      "travel drive": "",
      "number": 59429
    },
    {
      "name": "Songbird",
      "id": "tahlan_Nightingale",
      "designation": "Cruiser",
      "tech/manufacturer": "High Tech",
      "system id": "fortressshield",
      "fleet pts": 20,
      "hitpoints": 4000,
      "armor rating": 400,
      "max flux": 11000,
      "8/6/5/4%": "",
      "flux dissipation": 600,
      "ordnance points": 100,
      "fighter bays": 3,
      "max speed": 70,
      "acceleration": 60,
      "deceleration": 50,
      "max turn rate": 35,
      "turn acceleration": 50,
      "mass": 500,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 360,
      "shield upkeep": 0.3,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 20,
      "max crew": 100,
      "cargo": 140,
      "fuel": 110,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 9,
      "base value": 200000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 28,
      "supplies/mo": 28,
      "hints": "HIDE_IN_CODEX",
      "tags": "rare_bp, hist2t",
      "rarity": 0.2,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 59423
    },
    {
      "name": "Yari",
      "id": "tahlan_Glint",
      "designation": "Cruiser",
      "tech/manufacturer": "High Tech",
      "system id": "plasmajets",
      "fleet pts": 20,
      "hitpoints": 6000,
      "armor rating": 700,
      "max flux": 12000,
      "8/6/5/4%": "",
      "flux dissipation": 700,
      "ordnance points": 150,
      "fighter bays": "",
      "max speed": 70,
      "acceleration": 80,
      "deceleration": 50,
      "max turn rate": 30,
      "turn acceleration": 40,
      "mass": 1300,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.5,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 100,
      "max crew": 200,
      "cargo": 140,
      "fuel": 110,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 9,
      "base value": 210000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 25,
      "supplies/mo": 25,
      "hints": "",
      "tags": "rare_bp, hist2t, merc",
      "rarity": 0.5,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 59423
    },
    {
      "name": "Yukikaze",
      "id": "tahlan_Yukikaze",
      "designation": "Cruiser",
      "tech/manufacturer": "High Tech",
      "system id": "displacer",
      "fleet pts": 20,
      "hitpoints": 7000,
      "armor rating": 700,
      "max flux": 12000,
      "8/6/5/4%": "",
      "flux dissipation": 700,
      "ordnance points": 160,
      "fighter bays": "",
      "max speed": 80,
      "acceleration": 80,
      "deceleration": 50,
      "max turn rate": 50,
      "turn acceleration": 70,
      "mass": 1400,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 180,
      "shield upkeep": 0.5,
      "shield efficiency": 0.7,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 100,
      "cargo": 140,
      "fuel": 110,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 9,
      "base value": 220000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 360,
      "CR loss/sec": 0.25,
      "supplies/rec": 30,
      "supplies/mo": 30,
      "hints": "HIDE_IN_CODEX",
      "tags": "tahlan_kaze_bp",
      "rarity": 0.5,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 59423
    },
    {
      "name": "Prim",
      "id": "tahlan_Prim",
      "designation": "Drone",
      "tech/manufacturer": "High Tech",
      "system id": "",
      "fleet pts": "",
      "hitpoints": 250,
      "armor rating": 50,
      "max flux": 100,
      "8/6/5/4%": "",
      "flux dissipation": 10,
      "ordnance points": "",
      "fighter bays": "",
      "max speed": 400,
      "acceleration": 500,
      "deceleration": 500,
      "max turn rate": 100,
      "turn acceleration": 200,
      "mass": 10,
      "shield type": "NONE",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": "",
      "fuel": "",
      "fuel/ly": "",
      "range": "",
      "max burn": "",
      "base value": "",
      "cr %/day": "",
      "CR to deploy": "",
      "peak CR sec": "",
      "CR loss/sec": "",
      "supplies/rec": "",
      "supplies/mo": "",
      "hints": "HIDE_IN_CODEX",
      "tags": "",
      "rarity": "",
      "breakProb": 0,
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": 454
    },
    {
      "name": "Torii",
      "id": "tahlan_Torii",
      "designation": "Hunter Killer",
      "tech/manufacturer": "High Tech",
      "system id": "highenergyfocus",
      "fleet pts": 10,
      "hitpoints": 1500,
      "armor rating": 400,
      "max flux": 5000,
      "8/6/5/4%": "",
      "flux dissipation": 450,
      "ordnance points": 75,
      "fighter bays": "",
      "max speed": 110,
      "acceleration": 140,
      "deceleration": 110,
      "max turn rate": 80,
      "turn acceleration": 180,
      "mass": 450,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 30,
      "max crew": 70,
      "cargo": 90,
      "fuel": 40,
      "fuel/ly": 4,
      "range": 27,
      "max burn": 9,
      "base value": 30000,
      "cr %/day": 5,
      "CR to deploy": 15,
      "peak CR sec": 300,
      "CR loss/sec": 0.25,
      "supplies/rec": 10,
      "supplies/mo": 10,
      "hints": "",
      "tags": "hightech_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 445
    },
    {
      "name": "Haelequin",
      "id": "tahlan_Haelequin",
      "designation": "Fast Destroyer",
      "tech/manufacturer": "High Tech",
      "system id": "temporalshell",
      "fleet pts": 12,
      "hitpoints": 2800,
      "armor rating": 500,
      "max flux": 5000,
      "8/6/5/4%": "",
      "flux dissipation": 400,
      "ordnance points": 80,
      "fighter bays": "",
      "max speed": 100,
      "acceleration": 120,
      "deceleration": 100,
      "max turn rate": 65,
      "turn acceleration": 160,
      "mass": 500,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 40,
      "max crew": 80,
      "cargo": 110,
      "fuel": 50,
      "fuel/ly": 4,
      "range": 25,
      "max burn": 9,
      "base value": 35000,
      "cr %/day": 5,
      "CR to deploy": 15,
      "peak CR sec": 300,
      "CR loss/sec": 0.25,
      "supplies/rec": 20,
      "supplies/mo": 20,
      "hints": "",
      "tags": "rare_bp, hist1t",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 54
    },
    {
      "name": "Renki",
      "id": "tahlan_Renki",
      "designation": "Missile Frigate",
      "tech/manufacturer": "High Tech",
      "system id": "forgevats",
      "fleet pts": 8,
      "hitpoints": 1100,
      "armor rating": 250,
      "max flux": 2400,
      "8/6/5/4%": "",
      "flux dissipation": 150,
      "ordnance points": 40,
      "fighter bays": "",
      "max speed": 150,
      "acceleration": 170,
      "deceleration": 120,
      "max turn rate": 70,
      "turn acceleration": 150,
      "mass": 220,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 15,
      "max crew": 25,
      "cargo": 30,
      "fuel": 25,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 9,
      "base value": 15000,
      "cr %/day": 5,
      "CR to deploy": 15,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 8,
      "supplies/mo": 8,
      "hints": "",
      "tags": "hightech_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 46
    },
    {
      "name": "Skola",
      "id": "tahlan_Skola",
      "designation": "Frigate",
      "tech/manufacturer": "High Tech",
      "system id": "displacer",
      "fleet pts": 8,
      "hitpoints": 1200,
      "armor rating": 200,
      "max flux": 2600,
      "8/6/5/4%": "",
      "flux dissipation": 200,
      "ordnance points": 30,
      "fighter bays": "",
      "max speed": 180,
      "acceleration": 200,
      "deceleration": 160,
      "max turn rate": 80,
      "turn acceleration": 200,
      "mass": 200,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 10,
      "max crew": 20,
      "cargo": 25,
      "fuel": 20,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 11,
      "base value": 16000,
      "cr %/day": 5,
      "CR to deploy": 15,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 4,
      "supplies/mo": 4,
      "hints": "",
      "tags": "hightech_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 46
    },
    {
      "name": "Bungalow",
      "id": "tahlan_Bungalow",
      "designation": "Carrier",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_dodgynavigationfeed",
      "fleet pts": 15,
      "hitpoints": 8000,
      "armor rating": 1000,
      "max flux": 5000,
      "8/6/5/4%": "",
      "flux dissipation": 200,
      "ordnance points": 120,
      "fighter bays": 4,
      "max speed": 40,
      "acceleration": 20,
      "deceleration": 10,
      "max turn rate": 10,
      "turn acceleration": 10,
      "mass": 2000,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 1.1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 200,
      "max crew": 320,
      "cargo": 100,
      "fuel": 60,
      "fuel/ly": 4,
      "range": 15,
      "max burn": 8,
      "base value": 120000,
      "cr %/day": 4,
      "CR to deploy": 15,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 20,
      "supplies/mo": 20,
      "hints": "CARRIER",
      "tags": "lowtech_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 410
    },
    {
      "name": "Flagellator",
      "id": "tahlan_Flagellator",
      "designation": "Destroyer",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_crusherdrive",
      "fleet pts": 10,
      "hitpoints": 6000,
      "armor rating": 800,
      "max flux": 5000,
      "8/6/5/4%": "",
      "flux dissipation": 300,
      "ordnance points": 100,
      "fighter bays": "",
      "max speed": 90,
      "acceleration": 100,
      "deceleration": 60,
      "max turn rate": 40,
      "turn acceleration": 40,
      "mass": 450,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 50,
      "max crew": 90,
      "cargo": 70,
      "fuel": 70,
      "fuel/ly": 3,
      "range": 28,
      "max burn": 9,
      "base value": 35000,
      "cr %/day": 5,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 9,
      "supplies/mo": 9,
      "hints": "",
      "tags": "lowtech_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 13464
    },
    {
      "name": "Bronco",
      "id": "tahlan_Bronco",
      "designation": "Missile Destroyer",
      "tech/manufacturer": "Low Tech",
      "system id": "ammofeed",
      "fleet pts": 10,
      "hitpoints": 4000,
      "armor rating": 600,
      "max flux": 3500,
      "8/6/5/4%": "",
      "flux dissipation": 200,
      "ordnance points": 80,
      "fighter bays": "",
      "max speed": 70,
      "acceleration": 50,
      "deceleration": 20,
      "max turn rate": 30,
      "turn acceleration": 20,
      "mass": 500,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 50,
      "max crew": 90,
      "cargo": 120,
      "fuel": 80,
      "fuel/ly": 3,
      "range": 28,
      "max burn": 9,
      "base value": 36000,
      "cr %/day": 5,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 10,
      "supplies/mo": 10,
      "hints": "",
      "tags": "lowtech_bp",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 1134
    },
    {
      "name": "Darnus",
      "id": "tahlan_darnus",
      "designation": "Frigate",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_jauntdrive",
      "fleet pts": 8,
      "hitpoints": 1800,
      "armor rating": 400,
      "max flux": 4000,
      "8/6/5/4%": "",
      "flux dissipation": 300,
      "ordnance points": 50,
      "fighter bays": "",
      "max speed": 120,
      "acceleration": 180,
      "deceleration": 175,
      "max turn rate": 120,
      "turn acceleration": 270,
      "mass": 200,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.3,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 15,
      "max crew": 25,
      "cargo": 25,
      "fuel": 20,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 10,
      "base value": 60000,
      "cr %/day": 10,
      "CR to deploy": 20,
      "peak CR sec": 300,
      "CR loss/sec": 0.25,
      "supplies/rec": 13,
      "supplies/mo": 13,
      "hints": "",
      "tags": "rare_bp, hist2t",
      "rarity": 0.75,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 2,
      "travel drive": "",
      "number": 206
    },
    {
      "name": "Blockhead",
      "id": "tahlan_blockhead",
      "designation": "Cruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "damper",
      "fleet pts": 14,
      "hitpoints": 8000,
      "armor rating": 1200,
      "max flux": 9000,
      "8/6/5/4%": "",
      "flux dissipation": 400,
      "ordnance points": 130,
      "fighter bays": "",
      "max speed": 40,
      "acceleration": 25,
      "deceleration": 15,
      "max turn rate": 18,
      "turn acceleration": 15,
      "mass": 1500,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.5,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 45,
      "max crew": 100,
      "cargo": 300,
      "fuel": 100,
      "fuel/ly": 3,
      "range": 30,
      "max burn": 7,
      "base value": 70000,
      "cr %/day": 3,
      "CR to deploy": 20,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 22,
      "supplies/mo": 22,
      "hints": "",
      "tags": "lowtech_bp",
      "rarity": "",
      "breakProb": 0.6,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 411
    },
    {
      "name": "Hresvelgr",
      "id": "tahlan_Hresvelgr",
      "designation": "Fleetcarrier",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_defformation",
      "fleet pts": 28,
      "hitpoints": 14000,
      "armor rating": 1600,
      "max flux": 11000,
      "8/6/5/4%": "",
      "flux dissipation": 400,
      "ordnance points": 260,
      "fighter bays": 6,
      "max speed": 35,
      "acceleration": 20,
      "deceleration": 20,
      "max turn rate": 8,
      "turn acceleration": 10,
      "mass": 3100,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 180,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 800,
      "max crew": 1600,
      "cargo": 300,
      "fuel": 300,
      "fuel/ly": 15,
      "range": 20,
      "max burn": 7,
      "base value": 400000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 45,
      "supplies/mo": 45,
      "hints": "CARRIER, COMBAT, NO_AUTO_ESCORT",
      "tags": "rare_bp, hist3t",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 4,
      "travel drive": "",
      "number": 507
    },
    {
      "name": "Castella",
      "id": "tahlan_Castella",
      "designation": "Battlecarrier",
      "tech/manufacturer": "Low Tech",
      "system id": "damper",
      "fleet pts": 28,
      "hitpoints": 15000,
      "armor rating": 1400,
      "max flux": 11000,
      "8/6/5/4%": "",
      "flux dissipation": 600,
      "ordnance points": 240,
      "fighter bays": 5,
      "max speed": 30,
      "acceleration": 15,
      "deceleration": 15,
      "max turn rate": 8,
      "turn acceleration": 8,
      "mass": 3500,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 100,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 700,
      "max crew": 1500,
      "cargo": 300,
      "fuel": 300,
      "fuel/ly": 15,
      "range": 20,
      "max burn": 7,
      "base value": 400000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 40,
      "supplies/mo": 40,
      "hints": "CARRIER, COMBAT, NO_AUTO_ESCORT",
      "tags": "rare_bp, hist3t",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 4,
      "travel drive": "",
      "number": 507
    },
    {
      "name": "Bento (LP)",
      "id": "tahlan_Bento_lp",
      "designation": "Combat Tanker",
      "tech/manufacturer": "Luddic Path",
      "system id": "tahlan_crusherdrive",
      "fleet pts": 6,
      "hitpoints": 3000,
      "armor rating": 500,
      "max flux": 8000,
      "8/6/5/4%": "",
      "flux dissipation": 150,
      "ordnance points": 70,
      "fighter bays": 1,
      "max speed": 60,
      "acceleration": 40,
      "deceleration": 30,
      "max turn rate": 30,
      "turn acceleration": 40,
      "mass": 400,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0.5,
      "shield efficiency": 1.2,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 10,
      "max crew": 20,
      "cargo": 30,
      "fuel": 250,
      "fuel/ly": 1,
      "range": 240,
      "max burn": 9,
      "base value": 15000,
      "cr %/day": 6,
      "CR to deploy": 20,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 7,
      "supplies/mo": 7,
      "hints": "TANKER, COMBAT",
      "tags": "LP_bp",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 4,
      "travel drive": "",
      "number": 209
    },
    {
      "name": "Bento",
      "id": "tahlan_Bento",
      "designation": "Armored Tanker",
      "tech/manufacturer": "Low Tech",
      "system id": "reservewing",
      "fleet pts": 6,
      "hitpoints": 3000,
      "armor rating": 500,
      "max flux": 8000,
      "8/6/5/4%": "",
      "flux dissipation": 150,
      "ordnance points": 70,
      "fighter bays": 1,
      "max speed": 60,
      "acceleration": 40,
      "deceleration": 30,
      "max turn rate": 30,
      "turn acceleration": 40,
      "mass": 400,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0.5,
      "shield efficiency": 1.2,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 10,
      "max crew": 20,
      "cargo": 30,
      "fuel": 250,
      "fuel/ly": 1,
      "range": 240,
      "max burn": 9,
      "base value": 15000,
      "cr %/day": 6,
      "CR to deploy": 20,
      "peak CR sec": 240,
      "CR loss/sec": 0.25,
      "supplies/rec": 7,
      "supplies/mo": 7,
      "hints": "TANKER",
      "tags": "lowtech_bp",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 4,
      "travel drive": "",
      "number": 209
    },
    {
      "name": "Throne",
      "id": "tahlan_throne",
      "designation": "Cruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_fluxfeeder",
      "fleet pts": 15,
      "hitpoints": 7000,
      "armor rating": 1200,
      "max flux": 12000,
      "8/6/5/4%": "",
      "flux dissipation": 500,
      "ordnance points": 150,
      "fighter bays": "",
      "max speed": 70,
      "acceleration": 50,
      "deceleration": 40,
      "max turn rate": 22,
      "turn acceleration": 30,
      "mass": 1200,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.5,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 160,
      "max crew": 220,
      "cargo": 180,
      "fuel": 120,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 120000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 26,
      "supplies/mo": 26,
      "hints": "WEAPONS_FRONT_TO_BACK",
      "tags": "rare_bp, hist2t, merc",
      "rarity": 0.5,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 401
    },
    {
      "name": "Castigator",
      "id": "tahlan_Castigator",
      "designation": "Assault Cruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_stormdrive",
      "fleet pts": 16,
      "hitpoints": 10000,
      "armor rating": 1400,
      "max flux": 12000,
      "8/6/5/4%": "",
      "flux dissipation": 500,
      "ordnance points": 160,
      "fighter bays": "",
      "max speed": 50,
      "acceleration": 40,
      "deceleration": 30,
      "max turn rate": 20,
      "turn acceleration": 25,
      "mass": 1400,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 180,
      "max crew": 290,
      "cargo": 200,
      "fuel": 140,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 140000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 28,
      "supplies/mo": 28,
      "hints": "WEAPONS_FRONT_TO_BACK",
      "tags": "rare_bp, hist2t, merc",
      "rarity": 0.5,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 401
    },
    {
      "name": "Providence",
      "id": "tahlan_providence",
      "designation": "Battlecruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_fluxfeeder",
      "fleet pts": 25,
      "hitpoints": 12000,
      "armor rating": 1600,
      "max flux": 16000,
      "8/6/5/4%": "",
      "flux dissipation": 600,
      "ordnance points": 270,
      "fighter bays": "",
      "max speed": 60,
      "acceleration": 38,
      "deceleration": 24,
      "max turn rate": 16,
      "turn acceleration": 18,
      "mass": 2800,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.5,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 500,
      "max crew": 900,
      "cargo": 320,
      "fuel": 500,
      "fuel/ly": 12,
      "range": 38,
      "max burn": 8,
      "base value": 380000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 40,
      "supplies/mo": 40,
      "hints": "",
      "tags": "rare_bp, hist3t, merc",
      "rarity": 0.8,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 5,
      "travel drive": "",
      "number": 2202
    },
    {
      "name": "Nibelung",
      "id": "tahlan_Nibelung",
      "designation": "Fast Battleship",
      "tech/manufacturer": "Low Tech",
      "system id": "tahlan_auxthrusters",
      "fleet pts": 25,
      "hitpoints": 15000,
      "armor rating": 1600,
      "max flux": 22000,
      "8/6/5/4%": "",
      "flux dissipation": 800,
      "ordnance points": 300,
      "fighter bays": "",
      "max speed": 50,
      "acceleration": 30,
      "deceleration": 20,
      "max turn rate": 12,
      "turn acceleration": 15,
      "mass": 3200,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 200,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 600,
      "max crew": 1000,
      "cargo": 300,
      "fuel": 400,
      "fuel/ly": 12,
      "range": 33,
      "max burn": 7,
      "base value": 320000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 45,
      "supplies/mo": 45,
      "hints": "",
      "tags": "rare_bp, hist3t",
      "rarity": 0.8,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 5,
      "travel drive": "",
      "number": 2202
    },
    {
      "name": "Nessie",
      "id": "tahlan_Nessie",
      "designation": "Makeshift Phase Cruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "ammofeed",
      "fleet pts": 20,
      "hitpoints": 6000,
      "armor rating": 1100,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 500,
      "ordnance points": 120,
      "fighter bays": "",
      "max speed": 70,
      "acceleration": 50,
      "deceleration": 20,
      "max turn rate": 20,
      "turn acceleration": 20,
      "mass": 1300,
      "shield type": "PHASE",
      "defense id": "phasecloak",
      "shield arc": "",
      "shield upkeep": "",
      "shield efficiency": "",
      "phase cost": 0.05,
      "phase upkeep": 0.05,
      "min crew": 120,
      "max crew": 160,
      "cargo": 50,
      "fuel": 50,
      "fuel/ly": 6,
      "range": 16,
      "max burn": 7,
      "base value": 180000,
      "cr %/day": 5,
      "CR to deploy": 25,
      "peak CR sec": 360,
      "CR loss/sec": 0.25,
      "supplies/rec": 24,
      "supplies/mo": 24,
      "hints": "PHASE",
      "tags": "rare_bp, hist1t",
      "rarity": "",
      "breakProb": 0.8,
      "minPieces": 3,
      "maxPieces": 5,
      "travel drive": "",
      "number": 4212
    },
    {
      "name": "Castella (LP)",
      "id": "tahlan_Castella_lp",
      "designation": "Battleship",
      "tech/manufacturer": "Luddic Path",
      "system id": "tahlan_crusherdrive",
      "fleet pts": 28,
      "hitpoints": 18000,
      "armor rating": 1800,
      "max flux": 11000,
      "8/6/5/4%": "",
      "flux dissipation": 600,
      "ordnance points": 240,
      "fighter bays": "",
      "max speed": 60,
      "acceleration": 25,
      "deceleration": 15,
      "max turn rate": 10,
      "turn acceleration": 10,
      "mass": 3500,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 100,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 500,
      "max crew": 1200,
      "cargo": 300,
      "fuel": 300,
      "fuel/ly": 15,
      "range": 20,
      "max burn": 7,
      "base value": 400000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 40,
      "supplies/mo": 40,
      "hints": "",
      "tags": "rare_bp, luddic_path",
      "rarity": 0.6,
      "breakProb": 0.6,
      "minPieces": 2,
      "maxPieces": 4,
      "travel drive": "",
      "number": 507
    },
    {
      "name": "Phoca",
      "id": "tahlan_Phoca",
      "designation": "Light Cruiser",
      "tech/manufacturer": "Midline",
      "system id": "ammofeed",
      "fleet pts": 12,
      "hitpoints": 5500,
      "armor rating": 650,
      "max flux": 9000,
      "8/6/5/4%": "",
      "flux dissipation": 500,
      "ordnance points": 140,
      "fighter bays": "",
      "max speed": 80,
      "acceleration": 70,
      "deceleration": 40,
      "max turn rate": 30,
      "turn acceleration": 60,
      "mass": 650,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 200,
      "shield upkeep": 0.3,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 100,
      "max crew": 180,
      "cargo": 120,
      "fuel": 100,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 9,
      "base value": 80000,
      "cr %/day": 4,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 15,
      "supplies/mo": 15,
      "hints": "",
      "tags": "rare_bp, hist1t",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 400
    },
    {
      "name": "Kodai",
      "id": "tahlan_Kodai",
      "designation": "Cruiser",
      "tech/manufacturer": "Midline",
      "system id": "maneuveringjets",
      "fleet pts": 14,
      "hitpoints": 8000,
      "armor rating": 900,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 600,
      "ordnance points": 120,
      "fighter bays": "",
      "max speed": 60,
      "acceleration": 40,
      "deceleration": 25,
      "max turn rate": 20,
      "turn acceleration": 30,
      "mass": 1100,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 160,
      "shield upkeep": 0.4,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 170,
      "max crew": 300,
      "cargo": 300,
      "fuel": 120,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 110000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 22,
      "supplies/mo": 22,
      "hints": "",
      "tags": "rare_bp, hist2t",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 121212
    },
    {
      "name": "Raba",
      "id": "tahlan_raba",
      "designation": "Mining Barge",
      "tech/manufacturer": "Low Tech",
      "system id": "maneuveringjets",
      "fleet pts": 14,
      "hitpoints": 8000,
      "armor rating": 1100,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 400,
      "ordnance points": 110,
      "fighter bays": 2,
      "max speed": 60,
      "acceleration": 35,
      "deceleration": 21,
      "max turn rate": 16,
      "turn acceleration": 24,
      "mass": 1200,
      "shield type": "PHASE",
      "defense id": "damper",
      "shield arc": "",
      "shield upkeep": "",
      "shield efficiency": "",
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 140,
      "max crew": 240,
      "cargo": 500,
      "fuel": 120,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 90000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 18,
      "supplies/mo": 18,
      "hints": "",
      "tags": "rare_bp",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 121212
    },
    {
      "name": "Tempest (P)",
      "id": "tahlan_Tempest_P",
      "designation": "Frigate",
      "tech/manufacturer": "Pirate",
      "system id": "tahlan_weaponsoverdrive",
      "fleet pts": 8,
      "hitpoints": 1100,
      "armor rating": 200,
      "max flux": 2500,
      "8/6/5/4%": "",
      "flux dissipation": 200,
      "ordnance points": 50,
      "fighter bays": 1,
      "max speed": 180,
      "acceleration": 200,
      "deceleration": 175,
      "max turn rate": 90,
      "turn acceleration": 270,
      "mass": 200,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 120,
      "shield upkeep": 0.2,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 15,
      "max crew": 25,
      "cargo": 30,
      "fuel": 20,
      "fuel/ly": 1,
      "range": 20,
      "max burn": 11,
      "base value": 40000,
      "cr %/day": 10,
      "CR to deploy": 20,
      "peak CR sec": 180,
      "CR loss/sec": 0.25,
      "supplies/rec": 8,
      "supplies/mo": 8,
      "hints": "",
      "tags": "rare_bp",
      "rarity": 0.75,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 2,
      "travel drive": "",
      "number": 206
    },
    {
      "name": "Eagle (P)",
      "id": "tahlan_Eagle_P",
      "designation": "Cruiser",
      "tech/manufacturer": "Pirate",
      "system id": "tahlan_raiderjets",
      "fleet pts": 15,
      "hitpoints": 8000,
      "armor rating": 900,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 500,
      "ordnance points": 155,
      "fighter bays": 1,
      "max speed": 50,
      "acceleration": 30,
      "deceleration": 20,
      "max turn rate": 15,
      "turn acceleration": 20,
      "mass": 1200,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.4,
      "shield efficiency": 0.8,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 150,
      "max crew": 250,
      "cargo": 150,
      "fuel": 100,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 140000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 22,
      "supplies/mo": 22,
      "hints": "WEAPONS_FRONT_TO_BACK",
      "tags": "rare_bp",
      "rarity": 0.75,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 40111
    },
    {
      "name": "Cordite",
      "id": "tahlan_Cobalt",
      "designation": "Cruiser",
      "tech/manufacturer": "High Tech",
      "system id": "highenergyfocus",
      "fleet pts": 14,
      "hitpoints": 5000,
      "armor rating": 600,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 700,
      "ordnance points": 140,
      "fighter bays": "",
      "max speed": 90,
      "acceleration": 100,
      "deceleration": 80,
      "max turn rate": 30,
      "turn acceleration": 60,
      "mass": 750,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 160,
      "shield upkeep": 0.3,
      "shield efficiency": 0.7,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 70,
      "max crew": 140,
      "cargo": 60,
      "fuel": 80,
      "fuel/ly": 3,
      "range": 27,
      "max burn": 9,
      "base value": 120000,
      "cr %/day": 4,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 20,
      "supplies/mo": 20,
      "hints": "",
      "tags": "rare_bp, hist2t",
      "rarity": 0.75,
      "breakProb": 2,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": ""
    },
    {
      "name": "Poltergeist",
      "id": "tahlan_Poltergeist",
      "designation": "Phase Cruiser",
      "tech/manufacturer": "High Tech",
      "system id": "forgevats",
      "fleet pts": 22,
      "hitpoints": 7000,
      "armor rating": 1100,
      "max flux": 10000,
      "8/6/5/4%": "",
      "flux dissipation": 700,
      "ordnance points": 140,
      "fighter bays": "",
      "max speed": 60,
      "acceleration": 50,
      "deceleration": 40,
      "max turn rate": 18,
      "turn acceleration": 25,
      "mass": 1200,
      "shield type": "PHASE",
      "defense id": "phasecloak",
      "shield arc": "",
      "shield upkeep": "",
      "shield efficiency": "",
      "phase cost": 0.05,
      "phase upkeep": 0.05,
      "min crew": 60,
      "max crew": 110,
      "cargo": 125,
      "fuel": 160,
      "fuel/ly": 3,
      "range": 50,
      "max burn": 8,
      "base value": 230000,
      "cr %/day": 4,
      "CR to deploy": 20,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 30,
      "supplies/mo": 30,
      "hints": "PHASE",
      "tags": "rare_bp, hist3t",
      "rarity": "",
      "breakProb": "",
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": ""
    },
    {
      "name": "Castigator (XIV)",
      "id": "tahlan_Castigator_xiv",
      "designation": "Assault Cruiser",
      "tech/manufacturer": "XIV Battlegroup",
      "system id": "burndrive",
      "fleet pts": 16,
      "hitpoints": 10000,
      "armor rating": 1400,
      "max flux": 12000,
      "8/6/5/4%": "",
      "flux dissipation": 550,
      "ordnance points": 160,
      "fighter bays": "",
      "max speed": 50,
      "acceleration": 40,
      "deceleration": 30,
      "max turn rate": 20,
      "turn acceleration": 25,
      "mass": 1400,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 180,
      "max crew": 290,
      "cargo": 200,
      "fuel": 140,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 8,
      "base value": 140000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 28,
      "supplies/mo": 28,
      "hints": "WEAPONS_FRONT_TO_BACK",
      "tags": "rare_bp, hist3t",
      "rarity": 0.1,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 401
    },
    {
      "name": "Skysplitter",
      "id": "tahlan_skyrend",
      "designation": "Battlecruiser",
      "tech/manufacturer": "Midline",
      "system id": "highenergyfocus",
      "fleet pts": 25,
      "hitpoints": 11000,
      "armor rating": 700,
      "max flux": 18000,
      "8/6/5/4%": "",
      "flux dissipation": 1200,
      "ordnance points": 300,
      "fighter bays": 2,
      "max speed": 60,
      "acceleration": 90,
      "deceleration": 55,
      "max turn rate": 15,
      "turn acceleration": 20,
      "mass": 3000,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0.4,
      "shield efficiency": 1.2,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 350,
      "max crew": 500,
      "cargo": 250,
      "fuel": 250,
      "fuel/ly": 10,
      "range": 30,
      "max burn": 8,
      "base value": 380000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 660,
      "CR loss/sec": 0.25,
      "supplies/rec": 35,
      "supplies/mo": 35,
      "hints": "",
      "tags": "rare_bp",
      "rarity": "",
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 5,
      "travel drive": "",
      "number": 11311
    },
    {
      "name": "Nelson",
      "id": "tahlan_nelson",
      "designation": "Assault Cruiser",
      "tech/manufacturer": "Midline",
      "system id": "tahlan_boostthruster",
      "fleet pts": 16,
      "hitpoints": 9000,
      "armor rating": 1100,
      "max flux": 9000,
      "8/6/5/4%": "",
      "flux dissipation": 650,
      "ordnance points": 180,
      "fighter bays": "",
      "max speed": 60,
      "acceleration": 40,
      "deceleration": 30,
      "max turn rate": 18,
      "turn acceleration": 26,
      "mass": 1500,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 240,
      "shield upkeep": 0.4,
      "shield efficiency": 0.9,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 180,
      "max crew": 260,
      "cargo": 140,
      "fuel": 140,
      "fuel/ly": 4,
      "range": 38,
      "max burn": 8,
      "base value": 135000,
      "cr %/day": 4,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 26,
      "supplies/mo": 26,
      "hints": "WEAPONS_FRONT_TO_BACK",
      "tags": "rare_bp, merc",
      "rarity": "",
      "breakProb": "",
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": ""
    },
    {
      "name": "Tower",
      "id": "tahlan_tower",
      "designation": "Heavy Cruiser",
      "tech/manufacturer": "Low Tech",
      "system id": "ammofeed",
      "fleet pts": 15,
      "hitpoints": 10000,
      "armor rating": 1500,
      "max flux": 9000,
      "8/6/5/4%": "",
      "flux dissipation": 400,
      "ordnance points": 160,
      "fighter bays": 2,
      "max speed": 40,
      "acceleration": 25,
      "deceleration": 10,
      "max turn rate": 14,
      "turn acceleration": 14,
      "mass": 2100,
      "shield type": "FRONT",
      "defense id": "",
      "shield arc": 150,
      "shield upkeep": 0.4,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 180,
      "max crew": 320,
      "cargo": 150,
      "fuel": 150,
      "fuel/ly": 5,
      "range": 30,
      "max burn": 8,
      "base value": 130000,
      "cr %/day": 4,
      "CR to deploy": 12,
      "peak CR sec": 540,
      "CR loss/sec": 0.25,
      "supplies/rec": 26,
      "supplies/mo": 26,
      "hints": "",
      "tags": "rare_bp",
      "rarity": "",
      "breakProb": 0.4,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 404
    },
    {
      "name": "NX-A",
      "id": "tahlan_nxa",
      "designation": "Cruiser",
      "tech/manufacturer": "Unknown",
      "system id": "tahlan_phasebreaker",
      "fleet pts": 20,
      "hitpoints": 5000,
      "armor rating": 700,
      "max flux": 11000,
      "8/6/5/4%": "",
      "flux dissipation": 750,
      "ordnance points": 160,
      "fighter bays": "",
      "max speed": 80,
      "acceleration": 80,
      "deceleration": 50,
      "max turn rate": 50,
      "turn acceleration": 70,
      "mass": 1400,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 160,
      "shield upkeep": 0.4,
      "shield efficiency": 0.7,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 100,
      "cargo": 140,
      "fuel": 110,
      "fuel/ly": 3,
      "range": 33,
      "max burn": 9,
      "base value": 250000,
      "cr %/day": 3,
      "CR to deploy": 12,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 30,
      "supplies/mo": 30,
      "hints": "HIDE_IN_CODEX, PHASE",
      "tags": "",
      "rarity": 0.5,
      "breakProb": 0.5,
      "minPieces": 2,
      "maxPieces": 3,
      "travel drive": "",
      "number": 59423
    },
    {
      "name": "Equinox",
      "id": "tahlan_equinox",
      "designation": "Drone Battlecarrier",
      "tech/manufacturer": "Remnant",
      "system id": "tahlan_coordinatedstrike",
      "fleet pts": 30,
      "hitpoints": 20000,
      "armor rating": 1400,
      "max flux": 22000,
      "8/6/5/4%": 37500,
      "flux dissipation": 1000,
      "ordnance points": 300,
      "fighter bays": 4,
      "max speed": 50,
      "acceleration": 35,
      "deceleration": 25,
      "max turn rate": 8,
      "turn acceleration": 12,
      "mass": 3400,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 270,
      "shield upkeep": 0.4,
      "shield efficiency": 0.6,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": 250,
      "fuel": 400,
      "fuel/ly": 10,
      "range": 40,
      "max burn": 8,
      "base value": 480000,
      "cr %/day": 3,
      "CR to deploy": 15,
      "peak CR sec": 720,
      "CR loss/sec": 0.25,
      "supplies/rec": 40,
      "supplies/mo": 40,
      "hints": "UNBOARDABLE, HIDE_IN_CODEX",
      "tags": "remnant, auto_rec",
      "rarity": "",
      "breakProb": "",
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": ""
    },
    {
      "name": "Flare",
      "id": "tahlan_flare",
      "designation": "Droneship",
      "tech/manufacturer": "Remnant",
      "system id": "drone_strike",
      "fleet pts": 12,
      "hitpoints": 4500,
      "armor rating": 400,
      "max flux": 5000,
      "8/6/5/4%": 3750,
      "flux dissipation": 300,
      "ordnance points": 100,
      "fighter bays": 2,
      "max speed": 100,
      "acceleration": 80,
      "deceleration": 60,
      "max turn rate": 35,
      "turn acceleration": 55,
      "mass": 500,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 200,
      "shield upkeep": 0.4,
      "shield efficiency": 0.6,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 0,
      "max crew": 0,
      "cargo": 90,
      "fuel": 70,
      "fuel/ly": 2,
      "range": 30,
      "max burn": 10,
      "base value": 55000,
      "cr %/day": 5,
      "CR to deploy": 15,
      "peak CR sec": 420,
      "CR loss/sec": 0.25,
      "supplies/rec": 12,
      "supplies/mo": 12,
      "hints": "UNBOARDABLE, HIDE_IN_CODEX",
      "tags": "remnant, auto_rec",
      "rarity": "",
      "breakProb": "",
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": ""
    },
    {
      "name": "Landsknecht",
      "id": "tahlan_landsknecht",
      "designation": "Heavy Cruiser",
      "tech/manufacturer": "Midline",
      "system id": "tahlan_orion_device_mk2",
      "fleet pts": 16,
      "hitpoints": 11000,
      "armor rating": 800,
      "max flux": 11000,
      "8/6/5/4%": 11000,
      "flux dissipation": 700,
      "ordnance points": 160,
      "fighter bays": "",
      "max speed": 70,
      "acceleration": 50,
      "deceleration": 40,
      "max turn rate": 20,
      "turn acceleration": 30,
      "mass": 1500,
      "shield type": "OMNI",
      "defense id": "",
      "shield arc": 90,
      "shield upkeep": 0.3,
      "shield efficiency": 1,
      "phase cost": "",
      "phase upkeep": "",
      "min crew": 250,
      "max crew": 350,
      "cargo": 150,
      "fuel": 150,
      "fuel/ly": 4,
      "range": 38,
      "max burn": 8,
      "base value": 140000,
      "cr %/day": 4,
      "CR to deploy": 12,
      "peak CR sec": 480,
      "CR loss/sec": 0.25,
      "supplies/rec": 28,
      "supplies/mo": 28,
      "hints": "",
      "tags": "",
      "rarity": "",
      "breakProb": "",
      "minPieces": "",
      "maxPieces": "",
      "travel drive": "",
      "number": ""
    }
  ]

  export default ships